### Create course
POST localhost:8081/course/create
Content-Type: application/json

{
  "id": 5,
  "name": "BB6",
  "price": 100.0,
  "duration": "2026-12-12",
  "createdDate": "2023-12-12"
}

### Get byId
GET localhost:8081/course/byId/1

### Get all
GET localhost:8081/course/all

### Put
PUT localhost:8081/course/update/4
Content-Type: application/json

{
  "name": "Muzaffar",
  "price": 10.0,
  "duration": "2030-11-11",
  "createdDate": "2020-11-12"
}

###Delete course
DELETE localhost:8081/course/delete/1


### Get name,price,duration
GET localhost:8081/course/name/BB9/10.0/2030-11-11

### Get between
GET localhost:8081/course/between/10.0/100.0

### Get between
GET localhost:8081/course/between_date/2020-11-12/2023-12-12

### Pagination
GET localhost:8081/course/pagination?page=1&size=4

### PaginationCreatedDate
GET localhost:8081/course/created_date

### FilterWithPagination
POST localhost:8081/student/filter?page=3&size=3
Content-Type: application/json

{
  "name": "BB4",
  "price": "10"
}